# dump_dir: !!!CHANGE_THIS!!!
name: distilgpt2_83m_baseline
steps: 400
probe_freq: null
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 768
  n_layers: 6
  n_heads: 12
  head_dim: 64
  max_seqlen: 1024
  rope_theta: 10000.0
  multiple_of: 256
  weight_tying: true

data:
  root_dir: data/shuffled
  sources:
    dclm_baseline_1.0: 100.0
  batch_size: 8
  prefetch_size: 1024
  seq_len: 1024
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: tokenizers/cl_toplang_128k.tiktoken

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 200
    keep: 3
  eval:
    every: 40
    keep: -1

logging:
  freq: 1

async_eval_gpus: 8
eval:
  harness:
    tasks:
      - hellaswag
  validation:
    max_steps: 1000
  generator:
    max_tokens: 4096
    dtype: bf16