"""example inference script for blt"""

import torch
from blt.models.blt_model import ByteLatentTransformer


def main():
    print("[PASS] initializing blt inference example")
    
    # create model
    model = ByteLatentTransformer(
        d_model=256,
        num_layers=4,
        num_heads=8,
        d_ff=1024,
        max_patch_size=8,
        min_patch_size=2,
        entropy_threshold=0.5,
        use_async=True,
    )
    
    model.eval()
    
    # create prompt
    prompt_text = "hello world"
    prompt_bytes = prompt_text.encode('utf-8')
    prompt_tensor = torch.tensor(list(prompt_bytes), dtype=torch.long)
    
    print(f"[PASS] prompt: '{prompt_text}'")
    print(f"[PASS] prompt bytes: {list(prompt_bytes)}")
    
    # run inference
    with torch.no_grad():
        logits, patch_sizes = model(prompt_tensor)
    
    print(f"[PASS] number of patches: {len(patch_sizes)}")
    print(f"[PASS] patch sizes: {patch_sizes}")
    print(f"[PASS] output shape: {logits.shape}")
    
    # generate text
    print("\n[PASS] generating text...")
    with torch.no_grad():
        generated = model.generate(
            prompt_tensor,
            max_length=20,
            temperature=0.8,
        )
    
    # decode generated bytes
    generated_bytes = generated.numpy().tolist()
    try:
        generated_text = bytes(generated_bytes).decode('utf-8', errors='replace')
        print(f"[PASS] generated: '{generated_text}'")
    except:
        print(f"[ERROR] could not decode generated bytes")
        print(f"[PASS] raw bytes: {generated_bytes}")
    
    print("[PASS] inference example completed")


if __name__ == "__main__":
    main()
